version: '3'
services:
  #https://github.com/joeferner/redis-commander
  redis-ui:
    container_name: redis-ui
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"